- name: Build Archive
  script: |
    xcodebuild \
      -workspace ios.xcworkspace \
      -scheme ios \
      archive \
      -archivePath $CM_BUILD_DIR/build/app.xcarchive

- name: Export IPA
  script: |
    xcodebuild \
      -exportArchive \
      -archivePath $CM_BUILD_DIR/build/app.xcarchive \
      -exportPath $CM_BUILD_DIR/build/ipa \
      -exportOptionsPlist ExportOptions.plist
