workflows:
  ios-build:
    name: iOS IPA Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      xcode: latest
    scripts:
      - name: Extract source code
        script: |
          tar -xf ios_source.tar.gz
      - name: Generate Tuist Project
        script: |
          tuist generate
      - name: Build iOS App
        script: |
          xcodebuild -project ios.xcodeproj -scheme ios -configuration Release -sdk iphoneos -allowProvisioningUpdates
    artifacts:
      - build/ios/ipa/*.ipa

